use ffootball;

insert into nflTeam(name, abbreviation) values('Free Agent', 'FA');
insert into nflTeam(name, abbreviation) values('Arizona Cardinals', 'ARI');
insert into nflTeam(name, abbreviation) values('Atlanta Falcons', 'ATL');
insert into nflTeam(name, abbreviation) values('Baltimore Ravens', 'BAL');
insert into nflTeam(name, abbreviation) values('Buffalo Bills', 'BUF');
insert into nflTeam(name, abbreviation) values('Carolina Panthers', 'CAR');
insert into nflTeam(name, abbreviation) values('Chicago Bears', 'CHI');
insert into nflTeam(name, abbreviation) values('Cincinatti Bengals', 'CIN');
insert into nflTeam(name, abbreviation) values('Cleveland Browns', 'CLE');
insert into nflTeam(name, abbreviation) values('Dallas Cowboys', 'DAL');
insert into nflTeam(name, abbreviation) values('Denver Broncos', 'DEN');
insert into nflTeam(name, abbreviation) values('Detroit Lions', 'DET');
insert into nflTeam(name, abbreviation) values('Green Bay Packers', 'GB');
insert into nflTeam(name, abbreviation) values('Houston Texans', 'HOU');
insert into nflTeam(name, abbreviation) values('Indianapolis Colts', 'IND');
insert into nflTeam(name, abbreviation) values('Jacksonville Jaguars', 'JAX');
insert into nflTeam(name, abbreviation) values('Kansas City Chiefs', 'KC');
insert into nflTeam(name, abbreviation) values('Los Angeles Chargers', 'LAC');
insert into nflTeam(name, abbreviation) values('Los Angeles Rams', 'LAR');
insert into nflTeam(name, abbreviation) values('Miami Dolphins', 'MIA');
insert into nflTeam(name, abbreviation) values('Minnesota Vikings', 'MIN');
insert into nflTeam(name, abbreviation) values('New England Patriots', 'NE');
insert into nflTeam(name, abbreviation) values('New Orleans Saints', 'NO');
insert into nflTeam(name, abbreviation) values('New York Giants', 'NYG');
insert into nflTeam(name, abbreviation) values('New York Jets', 'NYJ');
insert into nflTeam(name, abbreviation) values('Oakland Raiders', 'OAK');
insert into nflTeam(name, abbreviation) values('Philadelphia Eagles', 'PHI');
insert into nflTeam(name, abbreviation) values('Pittsburgh Steelers', 'PIT');
insert into nflTeam(name, abbreviation) values('San Francisco 49ers', 'SF');
insert into nflTeam(name, abbreviation) values('Seattle Seahawks', 'SEA');
insert into nflTeam(name, abbreviation) values('Tampa Bay Buccaneers', 'TB');
insert into nflTeam(name, abbreviation) values('Tennessee Titans', 'TEN');
insert into nflTeam(name, abbreviation) values('Washington Redskins', 'WAS');


insert into player(firstname, lastname, positionkey) values('Arizona', 'Cardinals', 6);
insert into player(firstname, lastname, positionkey) values('Atlanta', 'Falcons', 6);
insert into player(firstname, lastname, positionkey) values('Baltimore', 'Ravens', 6);
insert into player(firstname, lastname, positionkey) values('Buffalo', 'Bills', 6);
insert into player(firstname, lastname, positionkey) values('Carolina', 'Panthers', 6);
insert into player(firstname, lastname, positionkey) values('Chicago', 'Bears', 6);
insert into player(firstname, lastname, positionkey) values('Cincinatti', 'Bengals', 6);
insert into player(firstname, lastname, positionkey) values('Cleveland', 'Browns', 6);
insert into player(firstname, lastname, positionkey) values('Dallas', 'Cowboys', 6);
insert into player(firstname, lastname, positionkey) values('Denver', 'Broncos', 6);
insert into player(firstname, lastname, positionkey) values('Detroit', 'Lions', 6);
insert into player(firstname, lastname, positionkey) values('Green Bay', 'Packers', 6);
insert into player(firstname, lastname, positionkey) values('Houston', 'Texans', 6);
insert into player(firstname, lastname, positionkey) values('Indianapolis', 'Colts', 6);
insert into player(firstname, lastname, positionkey) values('Jacksonville', 'Jaguars', 6);
insert into player(firstname, lastname, positionkey) values('Kansas City', 'Chiefs', 6);
insert into player(firstname, lastname, positionkey) values('Los Angeles', 'Chargers', 6);
insert into player(firstname, lastname, positionkey) values('Los Angeles', 'Rams', 6);
insert into player(firstname, lastname, positionkey) values('Miami', 'Dolphins', 6);
insert into player(firstname, lastname, positionkey) values('Minnesota', 'Vikings', 6);
insert into player(firstname, lastname, positionkey) values('New England', 'Patriots', 6);
insert into player(firstname, lastname, positionkey) values('New Orleans', 'Saints', 6);
insert into player(firstname, lastname, positionkey) values('New York', 'Giants', 6);
insert into player(firstname, lastname, positionkey) values('New York', 'Jets', 6);
insert into player(firstname, lastname, positionkey) values('Oakland', 'Raiders', 6);
insert into player(firstname, lastname, positionkey) values('Philadeplhia', 'Eagles', 6);
insert into player(firstname, lastname, positionkey) values('Pittsburgh', 'Steelers', 6);
insert into player(firstname, lastname, positionkey) values('San Francisco', '49ers', 6);
insert into player(firstname, lastname, positionkey) values('Seattle', 'Seahawks', 6);
insert into player(firstname, lastname, positionkey) values('Tampa Bay', 'Buccaneers', 6);
insert into player(firstname, lastname, positionkey) values('Tennessee', 'Titans', 6);
insert into player(firstname, lastname, positionkey) values('Washington', 'Redskins', 6);



